services:
  traefik:
    image: traefik:3.2
    container_name: traefik
    ports:
      - 127.0.0.1:90:90
      - 127.0.0.1:9090:9090
    volumes:
      - ./traefik:/etc/traefik/
  dvwa:
    image: yutony/web-dvwa:v1
    build: 
      dockerfile: ./Dockerfile.dvwa
    container_name: dvwa
  kali:
    image: yutony/kali:v1
    build: 
      dockerfile: ./Dockerfile.kali
    container_name: kali
    network_mode: host
    volumes:
      - ./kali-data:/kali-data
    working_dir: /kali-data
    tty: true
